version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_frontend
    hostname: frontend
    ports:
      - "8080:80"
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
      - BACKEND_HOST=backend
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./public:/usr/share/nginx/html:ro
    networks:
      fastapi_public_network:
        aliases:
          - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  fastapi_public_network:
    external: true
    name: fastapi_public_network