
services:
  db:
    image: postgres:13-alpine
    container_name: fastapi_db
    env_file:
      - .env  # Загружаем переменные из файла .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      fastapi_backend_network:
        aliases:
          - db.backend.internal

  backend:
    build: .
    container_name: fastapi_backend
    env_file:
      - .env  # Загружаем переменные из файла .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db.backend.internal:5432/${POSTGRES_DB}"
      SECRET_KEY: ${SECRET_KEY}
      API_BASE_URL: "http://backend:8000"
      PUBLIC_API_BASE_URL: "http://localhost:8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      fastapi_backend_network:
        aliases:
          - backend.internal
      fastapi_public_network:

volumes:
  postgres_data:

networks:
  fastapi_backend_network:
    internal: true
  fastapi_public_network:
    name: fastapi_public_network
    driver: bridge