version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Papik1952
      POSTGRES_DB: fastapi_db
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      fastapi_backend_network:
        aliases:
          - db.backend.internal

  backend:
    build: .
    container_name: fastapi_backend
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:Papik1952@db.backend.internal:5432/fastapi_db"
      SECRET_KEY: "your-very-secure-secret-key-here"
      API_BASE_URL: "http://backend:8000"  # Для внутренних ссылок
      PUBLIC_API_BASE_URL: "http://localhost:8000"  # Для внешнего доступа
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      fastapi_backend_network:
        aliases:
          - backend.internal
      fastapi_public_network:  # Сеть для связи с фронтендом

volumes:
  postgres_data:

networks:
  fastapi_backend_network:  # Приватная сеть для бэкенда и БД
    internal: true
  fastapi_public_network:   # Публичная сеть для связи с фронтендом
    name: fastapi_public_network
    driver: bridge